server:
  port: 8082
spring:
  application:
    name: consumer
  rabbitmq:
    addresses: localhost:5672
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/rabbit
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
#  batch:
#    job:
#      enabled: false

rabitmq:
  exchange:
    test: exchange.test
  queue:
    test: test-queue
  route-key:
    test: test-key

